### ISSUE TITLE
Feature Request: Option to delete old successful runs.

### ISSUE THREAD

**Issue by mk-pmb** [otto-de/purge-deprecated-workflow-runs#36]
Hi! This looks rather promising. However, I cannot find the option I want: To also delete successful runs that are older than x days, accepting fractions (0.5 = 12 hours). Could you add that, please?

Edit: In case anyone else needs a stopgap sooner, [I made one.](https://github.com/mk-pmb/github-ci-util-2405-pmb/tree/master/act/purge-old-workflow-runs)

**Comment by hanseartic** [comment]
💡Good idea. Will add another additional flag `remove-older-than`.

**Comment by rauldipeas** [comment]
This feature should support time period or number of builds to keep.

**Comment by hanseartic** [comment]
Fixed in https://github.com/otto-de/purge-deprecated-workflow-runs/releases/tag/v2.1.0
